[build]
  command = "ng build --configuration production"
  publish = "dist/club-taekwondo/browser"

# Redirection des APIs vers Railway
[[redirects]]
  from = "/api/*"
  to = "https://backend-club-taekwondo.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Redirection SPA pour Angular
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
