# Identité du projet (doit correspondre à ton projet créé dans SonarQube)
sonar.projectKey=frontend
sonar.projectName=Frontend Club Taekwondo

# Répertoires de code source
sonar.sources=src

# Exclure ce qu’on ne veut pas analyser
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**

# Répertoires de tests
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Rapport de couverture Angular
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# URL de ton serveur SonarQube local
sonar.host.url=http://localhost:9000
