# --- Identité du projet ---
sonar.projectKey=frontend
sonar.projectName=Frontend Club Taekwondo
sonar.sourceEncoding=UTF-8

# --- Code source & tests ---
sonar.sources=src
sonar.tests=src
# On n’exclut PAS les .spec.ts des sources globalement, on les identifie comme tests :
sonar.test.inclusions=**/*.spec.ts

# Ce qu’on veut ignorer de l’analyse (mais PAS les tests)
sonar.exclusions=**/node_modules/**,**/dist/**,**/assets/**,**/*.config.ts,**/environments/**

# On exclut les fichiers de test du calcul de couverture (pas du projet)
sonar.coverage.exclusions=**/*.spec.ts,**/environments/**,**/*.mock.ts,**/testing/**

# --- TypeScript ---
sonar.typescript.tsconfigPath=tsconfig.json

# --- Couverture (Angular CLI) ---
# Angular génère souvent coverage/<nom-projet>/lcov.info => on vise large
sonar.javascript.lcov.reportPaths=coverage/**/lcov.info
sonar.typescript.lcov.reportPaths=coverage/**/lcov.info

# --- Serveur SonarQube ---
sonar.host.url=http://localhost:9000
# sonar.login=<TOKEN>   # à passer en CLI ou via variable d’environnement, pas dans le fichier ;)
